name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint and Format
      run: |
        pip install flake8 black isort
        isort --check-only src/ tests/
        black --check src/ tests/
        flake8 src/ tests/

    - name: Run Unit Tests
      run: |
        pip install pytest
        pytest tests/ -v --cov=src --cov-report=xml  # С покрытием кода

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      if: success()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
